import java.text.SimpleDateFormat

plugins {
    id 'java-library'
    id 'net.nemerosa.versioning'      version '3.1.0'
    id 'com.vanniktech.maven.publish' version '0.35.0'
}

description = 'CVEScanner is a tool to get cves from NVD related to OpenJDK and GraalVM'

Date buildTimeAndDate = new Date()
ext {
    moduleName      = 'eu.hansolo.cvescanner'
    buildDate       = new SimpleDateFormat('yyyy-MM-dd').format(buildTimeAndDate)
    buildTime       = new SimpleDateFormat('HH:mm:ss.SSSZ').format(buildTimeAndDate)
    ciOssrhUsername = System.getenv('OSSRH_USERNAME')
    ciOssrhPassword = System.getenv('OSSRH_PASSWORD')
    ciGHUser        = System.getenv('GH_USER')
    ciGHToken       = System.getenv('GH_TOKEN')
    gpgkey          = System.getenv("GPG_PRIVATE_KEY")
    gpgpassphrase   = System.getenv("PASSPHRASE")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.google.code.gson:gson:2.13.2")
    implementation("eu.hansolo:jdktools:21.0.31")
    implementation("org.slf4j:slf4j-api:2.0.16")
    implementation("ch.qos.logback:logback-classic:1.5.15")
}

jar {
    from {
        //duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        //configurations.runtimeClasspath.collect {  it.isDirectory() ? it : zipTree(it)  }
    } {
        exclude "META-INF/*.SF"
        exclude "META-INF/*.DSA"
        exclude "META-INF/*.RSA"
    }
    manifest {
        attributes(
                'Built-By'              : System.properties['user.name'],
                'Created-By'            : System.properties['java.version'] + " (" + System.properties['java.vendor'] + " " + System.properties['java.vm.version'] + ")",
                'Build-Date'            : project.buildDate,
                'Build-Time'            : project.buildTime,
                'Build-Revision'        : versioning.info.commit,
                'Specification-Title'   : project.name,
                'Specification-Version' : project.version,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.version,
                'Bundle-Name'           : project.name,
                'Bundle-License'        : 'https://www.apache.org/licenses/LICENSE-2.0;description=Apache License Version 2.0;link=https://spdx.org/licenses/Apache-2.0.html',
                'Bundle-Description'    : description,
                'Bundle-Version'        : project.version,
                'Bundle-SymbolicName'   : 'eu.hansolo.cvescanner',
                'Class-Path'            : configurations.runtimeClasspath.files.collect { it.getName() }.join(' ')
        )
    }
}

if (JavaVersion.current().isJava8Compatible()) {
    allprojects {
        tasks.withType(Javadoc) {
            options.addStringOption('Xdoclint:none', '-quiet')
        }
    }
}

// create one jar for the javadoc
tasks.register('javadocJar', Jar) {
    dependsOn tasks.javadoc
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}

// create one jar for the source files
tasks.register('sourcesJar', Jar) {
    dependsOn tasks.classes
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives jar
    archives javadocJar
    archives sourcesJar
}

mavenPublishing {
    coordinates("eu.hansolo", "cvescanner", "${version}")

    pom {
        name = "CVEScanner"
        description = "CVEScanner is a tool to get cves from NVD related to OpenJDK and GraalVM"
        inceptionYear = "2025"
        url = "https://github.com/HanSolo/cvescanner/wiki"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = "HanSolo"
                name = "Gerrit Grunwald"
                email = "han.solo@mac.com"
                url = "https://github.com/HanSolo/"
            }
        }
        scm {
            url = "https://github.com/HanSolo/cvescanner/"
            connection = "scm:git:git://github.com/HanSolo/cvescanner.git"
            developerConnection = "scm:git:ssh://git@github.com/HanSolo/cvescanner.git"
        }
    }
}
